# Generated by Django 4.2.14 on 2026-08-18 20:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('installments_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAID', 'Pagada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta a Crédito',
                'verbose_name_plural': 'Ventas a Crédito',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(help_text='Número de cuota (1, 2, 3...)')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida')], default='PENDING', max_length=20)),
                ('credit_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credits.creditsale')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ('credit_sale', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('document_number', models.CharField(help_text='DNI, CUIT, etc.', max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['document_number'], name='credits_cus_documen_dbc9bf_idx'), models.Index(fields=['full_name'], name='credits_cus_full_na_ca915a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='credits.creditsale')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Ítem de Venta',
                'verbose_name_plural': 'Ítems de Venta',
            },
        ),
        migrations.AddField(
            model_name='creditsale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sales', to='credits.customer'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_at', models.DateField()),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.installment')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ('paid_at',),
                'indexes': [models.Index(fields=['installment', 'paid_at'], name='credits_pay_install_42bf19_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['status', 'due_date'], name='credits_ins_status_a74c93_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['credit_sale', 'status'], name='credits_ins_credit__737046_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('credit_sale', 'number')},
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['customer', 'status'], name='credits_cre_custome_9387d7_idx'),
        ),
        migrations.AddIndex(
            model_name='creditsale',
            index=models.Index(fields=['start_date'], name='credits_cre_start_d_8c5ba2_idx'),
        ),
    ]
