# Generated by Django 6.1 on 2026-08-19 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Tasa de interés en porcentaje (ej: 15 = 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_installments', models.PositiveIntegerField(default=1, help_text='Mínimo de cuotas permitidas', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_installments', models.PositiveIntegerField(default=24, help_text='Máximo de cuotas permitidas', validators=[django.core.validators.MinValueValidator(1)])),
                ('installment_options', models.CharField(default='1,3,6,9,12,18,24', help_text='Opciones rápidas de cuotas separadas por coma (ej: 1,3,6,12,24)', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Créditos',
                'verbose_name_plural': 'Configuración de Créditos',
            },
        ),
    ]
