# Generated by Django 6.1 on 2026-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Tienda Electrodomésticos', help_text='Nombre de la empresa', max_length=255)),
                ('phone', models.CharField(default='595987654321', help_text='Número de teléfono principal (ej: 595987654321)', max_length=20)),
                ('whatsapp_number', models.CharField(default='595987654321', help_text='Número de WhatsApp (ej: 595987654321)', max_length=20)),
                ('email', models.EmailField(default='info@tienda.com.py', help_text='Email de contacto', max_length=254)),
                ('address', models.TextField(default='Asunción, Paraguay', help_text='Dirección física de la empresa')),
                ('city', models.CharField(default='Asunción', help_text='Ciudad', max_length=100)),
                ('country', models.CharField(default='Paraguay', help_text='País', max_length=100)),
                ('facebook_url', models.URLField(blank=True, help_text='URL de Facebook')),
                ('instagram_url', models.URLField(blank=True, help_text='URL de Instagram')),
                ('twitter_url', models.URLField(blank=True, help_text='URL de Twitter/X')),
                ('youtube_url', models.URLField(blank=True, help_text='URL de YouTube')),
                ('business_hours', models.CharField(default='Lun-Vie: 8:00 - 18:00', help_text='Horarios de atención', max_length=100)),
                ('shipping_time', models.CharField(default='2-3 días en Asunción', help_text='Tiempo de envío', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
