# Generated by Django 6.1 on 2026-08-19 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_populate_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='inventory_p_categor_607069_idx',
            old_name='inventory_p_categor_b457a1_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='installment_interest_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Tasa de interés para compras en cuotas (en porcentaje, ej: 15 = 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio al contado', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
