# Generated by Django 6.1 on 2026-08-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_inventory_p_categor_b457a1_idx_inventory_p_categor_607069_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installment_options',
            field=models.CharField(blank=True, default='1,3,6,9,12,18,24', help_text='Opciones de cuotas disponibles (separadas por coma, ej: 1,3,6,9,12,18,24)', max_length=100),
        ),
    ]
